version: '3.8'

services:
  mongo-primary-server:
    container_name: mongo-primary-server
    image: mongo:4.4.18
    volumes:
      - /share/docker/mongo-replica-set/mongo-primary-server:/data
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongo-network
    ports:
      - 27021:27017
    links:
      - mongo-secondary-server1
      - mongo-secondary-server2
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "db-replica-set" ]
  mongo-secondary-server1:
    container_name: mongo-secondary-server1
    image: mongo:4.4.18
    volumes:
      - /share/docker/mongo-replica-set/mongo-secondary-server1:/data/db
    networks:
      - mongo-network
    ports:
      - 27022:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "db-replica-set" ]
  mongo-secondary-server2:
    container_name: mongo-secondary-server2
    image: mongo:4.4.18
    volumes:
      - /share/docker/mongo-replica-set/mongo-secondary-server2:/data/db
    networks:
      - mongo-network
    ports:
      - 27023:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "db-replica-set" ]

networks:
  mongo-network:
    driver: bridge